### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by huangenwu** [HFUT-VL/HFUT-VL-dataset#1]
兄弟，论文已经被收录了吧。能提前发下数据集下载连接吗？谢谢。

**Comment by EchoWangHF** [comment]
数据集已经可以下载了。

**Comment by huangenwu** [comment]
> 数据集已经可以下载了。

下载连接是在哪里的

**Comment by EchoWangHF** [comment]
不用下载链接啊，上面那个两个文件就是。VL1和VL2文件夹就是，下载下来就行。文件不是很大。
