### ISSUE TITLE
The HFUT-VL2 just includes 79 categories！ 

### ISSUE THREAD

**Issue by LonglongaaaGo** [HFUT-VL/HFUT-VL-dataset#3]
thanks for your share of the dataset.
but I find some problem in the HFUT-VL2：
the  categories of this dataset just has 79, and the “纳智捷” category has 400 images.

**Comment by WeeshawChen** [comment]
Thanks for your comment !

**Comment by WeeshawChen** [comment]
Thank you for your comment!
And our group has already set about recollecting  specific class of the dataset.
Please hold on a moment (probably before Sep 15 cos there some projects of group need to be followed), thanks again ~
